services:
  - type: web
    name: biolinksite
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: DB_PATH
        value: /var/data/data.db
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
